### ISSUE TITLE
Forced subtitles analytics

### ISSUE THREAD

**Issue by defagos** [SRGSSR/srgletterbox-apple#289]
**As an anlytics team member** I don't want to measure subtitles as being active if those are forced subtitles.

# Acceptance criteria

- No subtitles are returned in analytics labels when forced subtitles are selected.

# Tasks

- [ ] Check that forced subtitles are not returned as being enabled in streaming analytics.
- [ ] Fix if this is not the case.
- [ ] Check analytics with forced / unforced subtitles.
